from covid_19_au_grab.world_geodata.americas.ProcessCUMunicipality import process_cu_municipality
from covid_19_au_grab.world_geodata.americas.ProcessUSCounty import process_cu_municipality
from covid_19_au_grab.world_geodata.americas.ProcessBRCity import process_cu_municipality
from covid_19_au_grab.world_geodata.americas.ProcessCAHealthRegion import process_cu_municipality
from covid_19_au_grab.world_geodata.americas.ProcessCOMunicipality import process_cu_municipality

from covid_19_au_grab.world_geodata.mid_east.ProcessPSProvince import FIXME

from covid_19_au_grab.world_geodata.oceania.ProcessOtherAU import FIXME
from covid_19_au_grab.world_geodata.oceania.ProcessLGA import FIXME
from covid_19_au_grab.world_geodata.oceania.ProcessNZDHB import FIXME

from covid_19_au_grab.world_geodata.s_asia.ProcessBDDistrict import FIXME
from covid_19_au_grab.world_geodata.s_asia.ProcessINDistrict import FIXME
from covid_19_au_grab.world_geodata.s_asia.ProcessLKDistrict import FIXME
from covid_19_au_grab.world_geodata.s_asia.ProcessNPDistrict import FIXME
from covid_19_au_grab.world_geodata.s_asia.ProcessNPProvince import FIXME

from covid_19_au_grab.world_geodata.se_asia.ProcessTHDistrict import FIXME
from covid_19_au_grab.world_geodata.se_asia.ProcessJPCity import FIXME
from covid_19_au_grab.world_geodata.se_asia.ProcessMYDistrict import FIXME

from covid_19_au_grab.world_geodata.w_europe.ProcessCRCanton import FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessUKArea import FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessDEKreis import FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessESAutonomousCommunity import FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessESMadridMunicipality import FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessFRDepartment import  FIXME
from covid_19_au_grab.world_geodata.w_europe.ProcessITProvince import FIXME

from covid_19_au_grab.world_geodata.world.ProcessAdmin0 import FIXME
from covid_19_au_grab.world_geodata.world.ProcessAdmin1 import FIXME


if __name__ == '__main__':
    FIXME
